### ISSUE TITLE
Cannot resolve any symbols

### ISSUE THREAD

**Issue by PixelDough** [Mezo-hx/MonoGame.ImGuiNet#1]
When importing the nuget package (which seems to be up to date), none of my code is able to resolve any of the symbols mentioned in the brief guide, such as "ImGuiRenderer". There is no MonoGame.ImGuiNet namespace to import, despite the fact that the source code clearly uses the namespace. 

I'm not knowledgeable about how packages work, so it confuses me why I wouldn't be able to access the MonoGame.ImGuiNet namespace. I have ImGui.NET 1.87.7.1, which was mentioned as a dependency, and my project is set to use .net6

**Comment by Mezo-hx** [comment]
Ah Right, That was an issue I was unable to fix due to my limited knowledge in NuGet... You'll have to download the repository, go to your project, add the MonoGame.ImGuINet sln file and add a reference for it in your project

**Comment by Mezo-hx** [comment]
Right-Click your main solution file
![image](https://github.com/Mezo-hx/MonoGame.ImGuiNet/assets/47868851/cfb69b3c-b31b-4ec5-b3d3-c3e018cf6605)
Then click on Add > Existing Project
![image](https://github.com/Mezo-hx/MonoGame.ImGuiNet/assets/47868851/e21400a4-c79e-466e-ba37-b6b05018a0bf)
and  then locate where you downloaded the repository, and double click the `.csproj` file...

Then on your Main csproj file (the csproj file that was created when you made your project), Right-Click it, click Add > Project Reference

![image](https://github.com/Mezo-hx/MonoGame.ImGuiNet/assets/47868851/fe045179-c1e9-4e1f-910b-3a9c3083d49a)

then you should see the MonoGame.ImGuINet in the list of options, next click on the checkbox that's located at the left of the `MonoGame.ImGuINet` option, then click `OK`

**Comment by Ujinjinjin** [comment]
PR #10 should fix the issue

**Comment by Lurler** [comment]
Using the latest nuget package it still doesn't work, unfortunately.

> The type or namespace name 'ImGuiRenderer' could not be found (are you missing a using directive or an assembly reference?)
